/*
 * @Author: Detcx
 * @Date: 2019-02-13 16:49:54
 * @Last Modified by: Detcx
 * @Last Modified time: 2019-02-26 20:16:19
 * @Description: Global ActionTypes Format："WORD_WORD_WORD"
 */

export const SET_LOGINED_PENDING = 'SET_LOGINED_PENDING';
export const CHECK_LOGINED_STATUS = 'CHECK_LOGINED_STATUS';
export const LOGGED_STATUS_SUCCEEDED = 'LOGGED_STATUS_SUCCEEDED';
export const LOGGED_STATUS_FAILED = 'LOGGED_STATUS_FAILED';

export const USER_FETCH_REQUEST = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const RANDOM_FETCH_REQUEST = 'RANDOM_FETCH_REQUEST';
export const RANDOM_FETCH_SUCCEEDED = 'RANDOM_FETCH_SUCCEEDED';
export const RANDOM_FETCH_FAILED = 'RANDOM_FETCH_FAILED';

export const TOGGLE_HOME_BK = 'TOGGLE_HOME_BK';

export const TOGGLE_SOMEONE_BK = 'TOGGLE_SOMEONE_BK';

export const USERLIST_FETCH_REQUEST = 'USERLIST_FETCH_REQUEST';
export const USERLIST_FETCH_SUCCEEDED = 'USERLIST_FETCH_SUCCEEDED';
export const USERLIST_FETCH_FAILED = 'USERLIST_FETCH_FAILED';

export const NEED_TO_RELOGIN = 'NEED_TO_RELOGIN';
export const GOTO_LOGIN = 'GOTO_LOGIN';
